export const dataQuiz = [
  {
    id: 1,
    name: 'Bebek Pang Dangklek',
    topic: 'Perulangan',
    solved: 73,
    points: 2,
  },
  {
    id: 2,
    name: 'Pintu Ajaib',
    topic: 'Percabangan',
    solved: 54,
    points: 2,
  },
  {
    id: 3,
    name: 'Rotasi Matriks',
    topic: 'Array',
    solved: 42,
    points: 3,
  },
  {
    id: 4,
    name: 'Wildcard',
    topic: 'Subprogram',
    solved: 17,
    points: 4,
  },
  {
    id: 5,
    name: 'Tukang Sulap',
    topic: 'Subprogram',
    solved: 12,
    points: 4,
  },
  {
    id: 6,
    name: 'Membalik yang Terbalik',
    topic: 'Subprogram',
    solved: 21,
    points: 5,
  },
  {
    id: 7,
    name: 'Teman Dekat',
    topic: 'Subprogram',
    solved: 24,
    points: 4,
  },
  {
    id: 8,
    name: 'Gaya Bahasa Dangklek',
    topic: 'Pendalaman String',
    solved: 11,
    points: 5,
  },
  {
    id: 9,
    name: 'Pembuangan String',
    topic: 'Pendalaman String',
    solved: 20,
    points: 5,
  },
  {
    id: 10,
    name: 'Monolisa Terbalik',
    topic: 'Rekursi',
    solved: 14,
    points: 5,
  },
];
