export const dataTable = [
  {
    id: 1,
    username: 'bryanmax',
    solved: 73,
    concept: 35,
    rewards: 42,
    points: 197,
    bgColor: '#dbf6f6',
  },
  {
    id: 2,
    username: 'alrafi',
    solved: 61,
    concept: 24,
    rewards: 37,
    points: 112,
    bgColor: '#F9FACE',
  },
  {
    id: 3,
    username: 'star97',
    solved: 55,
    concept: 23,
    rewards: 30,
    points: 83,
    bgColor: '#dbf6f6',
  },
  {
    id: 4,
    username: 'merahputih',
    solved: 51,
    concept: 21,
    rewards: 28,
    points: 77,
    bgColor: '#dbf6f6',
  },
  {
    id: 5,
    username: 'kadalafrika',
    solved: 45,
    concept: 19,
    rewards: 27,
    points: 73,
    bgColor: '#dbf6f6',
  },
  {
    id: 6,
    username: 'ayokgass',
    solved: 44,
    concept: 17,
    rewards: 21,
    points: 65,
    bgColor: '#dbf6f6',
  },
  {
    id: 7,
    username: 'mutiara_',
    solved: 41,
    concept: 16,
    rewards: 19,
    points: 61,
    bgColor: '#dbf6f6',
  },
  {
    id: 8,
    username: 'sindan7',
    solved: 37,
    concept: 12,
    rewards: 17,
    points: 54,
    bgColor: '#dbf6f6',
  },
  {
    id: 9,
    username: 'victoryFX',
    solved: 34,
    concept: 11,
    rewards: 16,
    points: 49,
    bgColor: '#dbf6f6',
  },
  {
    id: 10,
    username: 'fantasusu',
    solved: 31,
    concept: 10,
    rewards: 14,
    points: 48,
    bgColor: '#dbf6f6',
  },
];
